services:
  scheduler:
    build:
      context: ..
      dockerfile: local_server/Dockerfile.scheduler
    env_file:
      - .env
    volumes:
      - ../functions:/workspace/functions:ro
      - ./src:/workspace/local_server/src:ro
      - ./tests:/workspace/local_server/tests:ro
      - /etc/cloudapi:/etc/cloudapi:ro
    ports:
      - "9090:9090"
    command: ["python", "-m", "local_server.scheduler"]

  telegram_polling:
    build:
      context: ..
      dockerfile: local_server/Dockerfile.telegram
    env_file:
      - .env
    volumes:
      - ../functions:/workspace/functions:ro
      - /etc/cloudapi:/etc/cloudapi:ro
    command: ["python", "/workspace/functions/telegram_bot/polling.py"]
